
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const App = lazy(() => import("./pages/App.tsx"));
const Camera = lazy(() => import("./pages/Camera.tsx"));
const Dashboard = lazy(() => import("./pages/Dashboard.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const Register = lazy(() => import("./pages/Register.tsx"));
const ResetPassword = lazy(() => import("./pages/ResetPassword.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <App />},
	{ path: "/camera", element: <Camera />},
	{ path: "/dashboard", element: <Dashboard />},
	{ path: "/login", element: <Login />},
	{ path: "/register", element: <Register />},
	{ path: "/reset-password", element: <ResetPassword />},
	{ path: "/resetpassword", element: <ResetPassword />},

];
